export const config = {
    CANVAS_W : 800,
    CANVAS_H : 800,
    CANVAS_TOP : 150,
    PLAYER_W : 40,
    PLAYER_H : 40,
    BOXES : [],
    DEAD_LIST : [],
    BOX_COUNT : 0,
    isGameOver : false,
    WINNER : '',
    IAM_PLAYERS : 1,
    ALL_PLAYERS : [],
    DEADLIST_H : 150,
    BOX_LEVEL : 12,
    PLAYER_E_TIME : 1,
    REBONE_TIME : 5,
    FPS : 1000 / 30,
};
