export const config = {
    CANVAS_W : 800,
    CANVAS_H : 800,
    CANVAS_TOP : 150,
    PLAYER_W : 40,
    PLAYER_H : 40,
    ALL_PLAYERS : [],
    BOXES : [],
    DEAD_LIST : [],
    BOX_COUNT : 0,
    isGameOver : false,
    WINNER : '',
    IAM_PLAYERS : 1,
    DEADLIST_H : 150,
    BOX_LEVEL : 8,
    PLAYER_E_TIME : 1,
    REBONE_TIME : 5,
    MAGMA_H : 30,
    MAGMA_WAVE : 10,
    FPS : 1000/60,
    GAME_TIME : 0,
};
