export const config = {
    CANVAS_W : 800,
    CANVAS_H : 1000,
    CANVAS_TOP : 200,
    PLAYER_W : 40,
    PLAYER_H : 40,
    BOXES : [],
    DEAD_LIST : [],
    BOX_COUNT : 0,
    isGameOver : false,
    WINNER : '',
    IAM_PLAYERS : 1,
    ALL_PLAYERS : [],
    DEADLIST_H : 200,
};
